export enum MutationsTypes {
  SET_PAINT_MODE = "SET_PAINT_MODE",
  CREATE_LAYER = "CREATE_LAYER",
  CREATE_PAGE = "CREATE_PAGE"
}

export enum ActionsTypes {
  SET_PAINT_MODE = "SET_PAINT_MODE",
  CREATE_LAYER = "CREATE_LAYER",
  CREATE_PAGE = "CREATE_PAGE"
}
